DROP TABLE CATALOGUE_Groupe4_EXT;
CREATE TABLE CATALOGUE_Groupe4_EXT(
	MARQUE 		varchar2(30), 
	NOM 		varchar2(20),
	PUISSANCE 	Number(6),
	LONGUEUR 	varchar2(20), 
	NB_PLACES 	Number(2),
	NB_PORTES 	Number(2),
	COULEUR 	varchar2(20), 
	OCCASION 	BOOLEAN,
	PRIX 		Number(8))
ORGANIZATION EXTERNAL (
TYPE ORACLE_HIVE 
DEFAULT DIRECTORY ORACLE_BIGDATA_CONFIG
ACCESS PARAMETERS 
(
com.oracle.bigdata.tablename=default.CATALOGUE_Groupe4_ONS_H_EXT
)
) 
REJECT LIMIT UNLIMITED;

DROP TABLE CLIENTS_3_Groupe4;
CREATE TABLE CLIENTS_3_Groupe4(
	AGE 					Number(3), 
	SEXE 					varchar2(2),
	TAUX 					Number(6),
	SITUATION_FAMILIALE 	varchar2(10), 
	NB_ENFANT_A_CHARGE 		varchar2(2),
	2_EME_VOITURE 			BOOLEAN,
	IMMATRICULATION 		varchar2(20)
ORGANIZATION EXTERNAL (
TYPE ORACLE_HIVE 
DEFAULT DIRECTORY ORACLE_BIGDATA_CONFIG
ACCESS PARAMETERS 
(
com.oracle.bigdata.tablename=default.CLIENTS_3_Groupe4_ONS_H_EXT
)
) 
REJECT LIMIT UNLIMITED;


DROP TABLE CLIENTS_11_Groupe4;
CREATE TABLE CLIENTS_11_Groupe4(
	AGE 					Number(3), 
	SEXE 					varchar2(2),
	TAUX 					Number(6),
	SITUATION_FAMILIALE 	varchar2(10), 
	NB_ENFANT_A_CHARGE 		varchar2(2),
	2_EME_VOITURE 			BOOLEAN,
	IMMATRICULATION 		varchar2(20)
ORGANIZATION EXTERNAL (
TYPE ORACLE_HIVE 
DEFAULT DIRECTORY ORACLE_BIGDATA_CONFIG
ACCESS PARAMETERS 
(
com.oracle.bigdata.tablename=default.CLIENTS_11_Groupe4_ONS_H_EXT
)
) 
REJECT LIMIT UNLIMITED;


DROP TABLE CO2_Groupe4_EXT;
CREATE TABLE CO2_Groupe4_EXT(
	MARQUE_MODELE 		varchar2(80), 
	BONUS_MALUS 		Number(8),
	REJETS_CO2 			Number(4),
	COUT_ENERGIE 		varchar2(10))
ORGANIZATION EXTERNAL (
TYPE ORACLE_HIVE 
DEFAULT DIRECTORY ORACLE_BIGDATA_CONFIG
ACCESS PARAMETERS 
(
com.oracle.bigdata.tablename=default.CO2_Groupe4_ONS_H_EXT
)
) 
REJECT LIMIT UNLIMITED;


DROP TABLE IMMATRICULATION_Groupe4_EXT;
CREATE TABLE IMMATRICULATION_Groupe4_EXT(
	IMMATRICULATION 	varchar2(20)
	MARQUE 				varchar2(30), 
	NOM 				varchar2(20),
	PUISSANCE 			Number(6),
	LONGUEUR 			varchar2(20), 
	NB_PLACES 			Number(2),
	NB_PORTES 			Number(2),
	COULEUR 			varchar2(20), 
	OCCASION 			BOOLEAN,
	PRIX 				Number(8))
ORGANIZATION EXTERNAL (
TYPE ORACLE_HIVE 
DEFAULT DIRECTORY ORACLE_BIGDATA_CONFIG
ACCESS PARAMETERS 
(
com.oracle.bigdata.tablename=default.IMMATRICULATION_Groupe4_ONS_H_EXT
)
) 
REJECT LIMIT UNLIMITED;


DROP TABLE MARKETING_Groupe4_EXT;
CREATE TABLE MARKETING_Groupe4_EXT(
	AGE 					Number(3), 
	SEXE 					varchar2(2),
	TAUX 					Number(6),
	SITUATION_FAMILIALE 	varchar2(10), 
	NB_ENFANT_A_CHARGE 		varchar2(2),
	2_EME_VOITURE 			BOOLEAN)
ORGANIZATION EXTERNAL (
TYPE ORACLE_HIVE 
DEFAULT DIRECTORY ORACLE_BIGDATA_CONFIG
ACCESS PARAMETERS 
(
com.oracle.bigdata.tablename=default.MARKETING_Groupe4_ONS_H_EXT
)
) 
REJECT LIMIT UNLIMITED;